#!/bin/bash
# Usage: bash test-correct F1.inp F2.inp ...
#     Runs each F.inp through java enigma.Main and compares the output to 
#     F.out.  Briefly reports results.  Exits normally if all tests pass, and
#     otherwise exits with code 1.

code=0
rm -f OUT.txt
for f in "$@"; do
    echo -n "$f: "
    d="$(dirname "$f")"
    b="$d/$(basename "$f" .inp)"
    if [ -f "$b.conf" ]; then
        config="$b.conf"
    else
        config="$d/default.conf"
    fi
    if (ulimit -t 5; ulimit -f 100; 
        java -ea enigma.Main  "$config" "$f" OUT.txt 2>&1); then
	if diff -b OUT.txt "$b.out" >/dev/null; then
	    echo "OK";
	else
	    code=1; echo "ERROR (output)";
	fi;
    else
	code=1; echo "ERROR (bad exit)";
    fi;
    rm -rf OUT.txt
done;

exit $code
        
